# misc.tf
# All other resources (Config rules, SES, GuardDuty, SSM docs, Step Functions, API Gateway, CI/CD, etc.)
#
# Resource types in this file:
#   - aws_accessanalyzer_analyzer
#   - aws_acm_certificate
#   - aws_acmpca_certificate_authority
#   - aws_amplify_app
#   - aws_api_gateway_rest_api
#   - aws_api_gateway_vpc_link
#   - aws_apigatewayv2_api
#   - aws_appconfig_application
#   - aws_appconfig_deployment_strategy
#   - aws_appflow_flow
#   - aws_appintegrations_event_integration
#   - aws_appmesh_mesh
#   - aws_apprunner_auto_scaling_configuration_version
#   - aws_apprunner_connection
#   - aws_apprunner_service
#   - aws_apprunner_vpc_connector
#   - aws_appstream_fleet
#   - aws_appstream_image_builder
#   - aws_appstream_stack
#   - aws_appsync_graphql_api
#   - aws_athena_data_catalog
#   - aws_athena_workgroup
#   - aws_batch_compute_environment
#   - aws_batch_job_definition
#   - aws_batch_job_queue
#   - aws_batch_scheduling_policy
#   - aws_bedrock_guardrail
#   - aws_budgets_budget
#   - aws_ce_anomaly_monitor
#   - aws_ce_anomaly_subscription
#   - aws_cleanrooms_collaboration
#   - aws_cloud9_environment_ec2
#   - aws_cloudformation_stack
#   - aws_cloudformation_stack_set
#   - aws_cloudtrail
#   - aws_codeartifact_domain
#   - aws_codeartifact_repository
#   - aws_codebuild_project
#   - aws_codecommit_repository
#   - aws_codeconnections_connection
#   - aws_codedeploy_app
#   - aws_codedeploy_deployment_config
#   - aws_codepipeline
#   - aws_codepipeline_webhook
#   - aws_codestarconnections_connection
#   - aws_codestarconnections_host
#   - aws_cognito_identity_pool
#   - aws_cognito_user_pool
#   - aws_comprehend_document_classifier
#   - aws_comprehend_entity_recognizer
#   - aws_config_config_rule
#   - aws_connect_instance
#   - aws_connect_phone_number
#   - aws_dataexchange_data_set
#   - aws_datapipeline_pipeline
#   - aws_datasync_task
#   - aws_dax_cluster
#   - aws_detective_graph
#   - aws_devicefarm_instance_profile
#   - aws_devicefarm_project
#   - aws_devicefarm_test_grid_project
#   - aws_directory_service_directory
#   - aws_dlm_lifecycle_policy
#   - aws_dms_endpoint
#   - aws_dms_event_subscription
#   - aws_dms_replication_instance
#   - aws_dms_replication_subnet_group
#   - aws_dms_replication_task
#   - aws_ec2_carrier_gateway
#   - aws_ec2_client_vpn_endpoint
#   - aws_ec2_traffic_mirror_filter
#   - aws_ec2_traffic_mirror_session
#   - aws_ec2_traffic_mirror_target
#   - aws_efs_access_point
#   - aws_efs_file_system
#   - aws_egress_only_internet_gateway
#   - aws_elastic_beanstalk_application
#   - aws_elastic_beanstalk_environment
#   - aws_emr_cluster
#   - aws_emrcontainers_virtual_cluster
#   - aws_emrserverless_application
#   - aws_fis_experiment_template
#   - aws_fsx_lustre_file_system
#   - aws_glacier_vault
#   - aws_globalaccelerator_accelerator
#   - aws_glue_catalog_database
#   - aws_glue_catalog_table
#   - aws_glue_crawler
#   - aws_glue_job
#   - aws_glue_ml_transform
#   - aws_glue_registry
#   - aws_glue_trigger
#   - aws_grafana_workspace
#   - aws_guardduty_detector
#   - aws_imagebuilder_component
#   - aws_imagebuilder_container_recipe
#   - aws_imagebuilder_distribution_configuration
#   - aws_imagebuilder_image
#   - aws_imagebuilder_image_pipeline
#   - aws_imagebuilder_image_recipe
#   - aws_imagebuilder_infrastructure_configuration
#   - aws_iot_authorizer
#   - aws_iot_billing_group
#   - aws_iot_ca_certificate
#   - aws_iot_certificate
#   - aws_iot_policy
#   - aws_iot_provisioning_template
#   - aws_iot_role_alias
#   - aws_iot_thing
#   - aws_iot_thing_group
#   - aws_iot_thing_type
#   - aws_iot_topic_rule
#   - aws_ivs_channel
#   - aws_ivs_recording_configuration
#   - aws_kinesis_analytics_application
#   - aws_kinesis_firehose_delivery_stream
#   - aws_kinesis_stream
#   - aws_kinesis_video_stream
#   - aws_lexv2models_bot
#   - aws_mediaconnect_flow
#   - aws_mq_broker
#   - aws_mq_configuration
#   - aws_msk_cluster
#   - aws_msk_configuration
#   - aws_mwaa_environment
#   - aws_networkfirewall_firewall
#   - aws_networkfirewall_firewall_policy
#   - aws_networkfirewall_rule_group
#   - aws_networkmanager_core_network
#   - aws_networkmanager_device
#   - aws_networkmanager_global_network
#   - aws_networkmanager_link
#   - aws_oam_sink
#   - aws_opensearch_domain
#   - aws_opensearchserverless_collection
#   - aws_pipes_pipe
#   - aws_prometheus_rule_group_namespace
#   - aws_prometheus_workspace
#   - aws_ram_resource_share
#   - aws_redshift_cluster
#   - aws_redshift_event_subscription
#   - aws_redshift_parameter_group
#   - aws_redshift_snapshot_copy_grant
#   - aws_redshift_snapshot_schedule
#   - aws_redshift_subnet_group
#   - aws_redshift_usage_limit
#   - aws_resourcegroups_group
#   - aws_rum_app_monitor
#   - aws_s3control_storage_lens_configuration
#   - aws_sagemaker_app
#   - aws_sagemaker_app_image_config
#   - aws_sagemaker_code_repository
#   - aws_sagemaker_domain
#   - aws_sagemaker_endpoint
#   - aws_sagemaker_endpoint_configuration
#   - aws_sagemaker_feature_group
#   - aws_sagemaker_flow_definition
#   - aws_sagemaker_human_task_ui
#   - aws_sagemaker_image
#   - aws_sagemaker_image_version
#   - aws_sagemaker_model
#   - aws_sagemaker_model_package_group
#   - aws_sagemaker_notebook_instance
#   - aws_sagemaker_notebook_instance_lifecycle_configuration
#   - aws_sagemaker_pipeline
#   - aws_sagemaker_project
#   - aws_sagemaker_space
#   - aws_sagemaker_user_profile
#   - aws_sagemaker_workforce
#   - aws_sagemaker_workteam
#   - aws_scheduler_schedule_group
#   - aws_schemas_discoverer
#   - aws_service_discovery_service
#   - aws_ses_configuration_set
#   - aws_ses_domain_identity
#   - aws_sfn_activity
#   - aws_sfn_state_machine
#   - aws_shield_protection
#   - aws_shield_protection_group
#   - aws_signer_signing_profile
#   - aws_spot_fleet_request
#   - aws_spot_instance_request
#   - aws_ssm_association
#   - aws_ssm_document
#   - aws_ssm_maintenance_window
#   - aws_ssm_maintenance_window_target
#   - aws_ssm_maintenance_window_task
#   - aws_ssm_resource_data_sync
#   - aws_ssmincidents_response_plan
#   - aws_storagegateway_gateway
#   - aws_synthetics_canary
#   - aws_synthetics_group
#   - aws_transfer_connector
#   - aws_transfer_server
#   - aws_transfer_user
#   - aws_transfer_workflow
#   - aws_verifiedaccess_endpoint
#   - aws_verifiedaccess_group
#   - aws_verifiedaccess_instance
#   - aws_verifiedaccess_trust_provider
#   - aws_verifiedpermissions_policy_store
#   - aws_workspaces_workspace
#   - aws_xray_sampling_rule
#
# Total: 203 resource type(s)
